export const containers = [
  {
    id: '1',
    name: 'Software Project 1',
    description:
      'The software project currently in development is a cloud-based project management tool designed to streamline team collaboration and increase productivity by providing real-time updates and task management capabilities.',
    created: '23/05/2022',
    createdBy: 'Peter Wilson',
    owner: 'Karen Smith',
    resourceCount: 24,
    monthlyCosts: '8,726.00',
    currency: 'USD',
    providers: ['AWS', 'Azure'],
    data: [
      { value: 4000 },
      { value: 3000 },
      { value: 2000 },
      { value: 2780 },
      { value: 1890 },
      { value: 2380 },
      { value: 3980 },
    ],
  },
  {
    id: '2',
    name: 'Software Project 45',
    description:
      'Our team is developing a cutting-edge mobile application that revolutionizes how users manage their personal finances, with advanced features for budgeting, expense tracking, and investment analysis.',
    created: '03/02/2021',
    createdBy: 'Claire Jones',
    owner: 'Sally Smith',
    resourceCount: 3,
    monthlyCosts: '783.00',
    currency: 'USD',
    providers: ['Azure'],
    data: [
      { value: 1290 },
      { value: 1120 },
      { value: 2910 },
      { value: 2370 },
      { value: 2630 },
      { value: 2530 },
      { value: 2180 },
    ],
  },
  {
    id: '3',
    name: 'Backup for IT',
    description:
      'Our software development project focuses on creating an AI-powered chatbot for customer support, capable of understanding natural language queries, providing instant responses, and escalating complex issues to human agents when necessary, improving overall service efficiency and customer engagement.',
    created: '29/11/2021',
    createdBy: 'Arnold Davis',
    owner: 'Carrie Jones',
    resourceCount: 17,
    monthlyCosts: '95, 263.00',
    currency: 'EUR',
    providers: ['AWS'],
    data: [
      { value: 14000 },
      { value: 16780 },
      { value: 19820 },
      { value: 23090 },
      { value: 27890 },
      { value: 47890 },
      { value: 65290 },
    ],
  },
  {
    id: '4',
    name: 'SQL DB for Finance',
    description:
      'We are working on a web-based e-commerce platform that provides seamless integration with popular payment gateways, efficient inventory management, and personalized shopping experiences to enhance customer satisfaction and drive sales',
    created: '13/01/2023',
    createdBy: 'Donald Martin',
    owner: 'Harry Wells',
    resourceCount: 5,
    monthlyCosts: '23,543.00',
    currency: 'USD',
    providers: ['AWS', 'Azure'],
    data: [
      { value: 47000 },
      { value: 38500 },
      { value: 32090 },
      { value: 25780 },
      { value: 21890 },
      { value: 23880 },
      { value: 13980 },
    ],
  },
  {
    id: '5',
    name: 'Software Project 2',
    description: 'Description 2',
    created: '13/01/2023',
    createdBy: 'Donald Martin',
    owner: 'Harry Wells',
    resourceCount: 5,
    monthlyCosts: '23,543.00',
    currency: 'USD',
    providers: ['AWS', 'Azure'],
    data: [
      { value: 87000 },
      { value: 38500 },
      { value: 132090 },
      { value: 25780 },
      { value: 21890 },
      { value: 23880 },
      { value: 13980 },
    ],
  },
];

export const costContainers = {
  containers: containers,
  isLoading: false,
  error: null,
};
