import { ISidebarItem } from '../../../types/menu-types';

export const helpCentreCategories: ISidebarItem[] = [
  {
    title: 'Account & Setup',
    id: '65c8cdbe67367cae14bcabb9',
    active: true,
    items: [
      {
        id: '65c8cdbe67367cae14bbabb9',
        title: 'Account Management',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Account',
        tags: [],
        summary: 'The Privacy Policy for DDIWare',
        active: true,
      },
      {
        id: '65c8cdbe67367cae14bbabc9',
        title: 'Account Security',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Account',
        tags: [],
        summary: 'Secure your account',
        active: true,
      },
      {
        id: '65c8cdbe67367cae14baabb9',
        title: 'Billing',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Account',
        tags: [],
        summary: 'Billing',
        active: true,
      },
    ],
  },
  {
    title: 'Cost Containers',
    id: '65c8cdbe67367cae14bcabb9',
    active: true,
    items: [
      {
        id: '65c8cdbe67367cae14bbabb9',
        title: 'Creating a Cost Container',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Containers',
        tags: [],
        summary: 'Create a cost container',
      },
      {
        id: '65c8cdbe67367cae14bbabc9',
        title: 'Delete a Cost Container',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Containers',
        tags: [],
        summary: 'Delete a cost container',
        active: true,
      },
      {
        id: '65c8cdbe67367cae14baabb9',
        title: 'Update a Cost Container',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Containers',
        tags: [],
        summary: 'Update a cost container',
        active: true,
      },
    ],
  },
  {
    title: 'Settings',
    id: '63c8cdbe67367cae14bcabb9',
    active: true,
    items: [
      {
        id: '65c8cdbe67367cae14bbabb9',
        title: 'Delete my account',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Settings',
        tags: [],
        summary: 'How to delete your account',
        active: true,
      },
    ],
  },
  {
    title: 'Legal & Compliance',
    id: '63c8cdbe67367cce14bcabb9',
    active: true,
    items: [
      {
        id: '65c8cdbe67367cae14bbabb9',
        title: 'Privacy Policy',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Legal & Compliance',
        tags: [],
        summary: 'Privacy Policy for DDIWare',
        active: true,
      },
      {
        id: '65c8cdbe67367cae14bbabb9',
        title: 'Terms of Service',
        lastUpdatedDate: '2023-09-15T00:00:00Z',
        category: 'Legal & Compliance',
        tags: [],
        summary: 'Terms of Service for DDIWare',
        active: true,
      },
    ],
  },
];
