parameters:
  - name: tenantId
    type: string
    default: ''
  - name: branch
    type: string
    default: 'main'
  - name: environment
    type: string
    default: ''
  - name: subscriptionId
    type: string
    default: ''
  - name: kvServiceConnection
    type: string
    default: ''
  - name: deploymentKeyVaultName
    type: string
    default: ''
  - name: apiUrl
    type: string
    default: ''
  - name: adoEnvironment
    type: string
    default: ''
  - name: runTests
    type: boolean
    default: true

steps:
  - task: PowerShell@2
    displayName: Dump Environment Variables
    inputs:
      targetType: 'inline'
      script: |
        dir env: | Format-Table -wrap
  - script: |
      npm install
      if [ "${{parameters.environment}}" == "dev" ]; then
        npm version patch --force
      fi
      npm run build-${{parameters.environment}}
    displayName: npm install, build
  - ${{ if parameters.runTests}}:
      - template: test.ui.yaml
  - script: (cd build && zip -r $(Build.ArtifactStagingDirectory)/build-${{parameters.environment}}.zip .)
    displayName: Zip Deployment
    condition: succeeded()
  - publish: $(Build.ArtifactStagingDirectory)/build-${{parameters.environment}}.zip
    displayName: Publish Artifacts
    condition: succeeded()
    artifact: App-${{parameters.environment}}
