steps:
  - task: PowerShell@2
    displayName: Dump Environment Variables
    inputs:
      targetType: 'inline'
      script: |
        dir env: | Format-Table -wrap
  - script: |
      npm install
      npm run build-${{parameters.environment}}
    displayName: npm install, build
  - script: |
      npm run test -- --coverage --watchAll=false --ci --reporters=default --reporters=jest-junit --coverageReporters=cobertura
    displayName: 'Test with code coverage'
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      failTaskOnFailedTests: true
      mergeTestResults: true
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
      failIfCoverageEmpty: false
