trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  tenantId: 90598989-b884-4fc1-999f-d176a8e1a54e
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  envDev: dev
  envProd: prod
  kvServiceConnectionDev: DEV KV Service Connection
  kvServiceConnectionProd: PROD KV Service Connection
  subscriptionId: 94e4237e-953e-4c21-9a4e-fc3f3699d9e4
  kvServiceConnection: DEV KV Service Connection
  apiUrlDev: 'https://api.dev.costoptix.com'
  apiUrlProd: 'https://api.costoptix.com'
  runE2ETests: false

stages:
  - stage: BuildStage
    displayName: Build and Test Dev
    jobs:
      - job: BuildDev
        displayName: Build and Test Dev
        steps:
          - template: ./templates/build.ui.yaml
            parameters:
              tenantId: ${{variables.tenantId}}
              environment: ${{variables.envDev}}
              subscriptionId: ${{variables.subscriptionId}}
              kvServiceConnection: ${{variables.kvServiceConnectionDev}}
              apiUrl: ${{variables.apiUrlDev}}
              adoEnvironment: ${{variables.adoEnvironment}}
              runTests: true
      - job: BuildProd
        displayName: Build and Test Prod
        dependsOn: BuildDev
        condition: succeeded('BuildDev')
        steps:
          - template: ./templates/build.ui.yaml
            parameters:
              tenantId: ${{variables.tenantId}}
              environment: ${{variables.envProd}}
              subscriptionId: ${{variables.subscriptionId}}
              kvServiceConnection: ${{variables.kvServiceConnectionProd}}
              apiUrl: ${{variables.apiUrlProd}}
              adoEnvironment: ${{variables.adoEnvironment}}
              runTests: false

  - stage: DeployDevStage
    displayName: Deploy Dev
    dependsOn: BuildStage
    condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
    jobs:
      - deployment: DeployDevJob
        displayName: Deploy DEV
        environment: DEV-App
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./templates/deploy.ui.yaml
                  parameters:
                    environment: ${{variables.envDev}}
                    subscriptionId: ${{variables.subscriptionId}}
                    kvServiceConnection: ${{variables.kvServiceConnectionDev}}

  - stage: RunE2ETests
    displayName: Run Dev E2E Tests
    dependsOn: DeployDevStage
    condition: and(succeeded(), eq(variables.isPullRequest, 'false'), eq(variables.runE2ETests, 'true'))
    jobs:
      - job: RunE2ETests
        displayName: Run E2E Tests
        steps:
          - template: ./templates/e2e-testing.yaml
            parameters:
              url: dev.costoptix.com

  - stage: DeployProdStage
    displayName: Deploy Prod
    dependsOn: DeployDevStage
    condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
    jobs:
      - deployment: DeployProdJob
        displayName: Deploy Prod
        environment: Prod-App
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./templates/deploy.ui.yaml
                  parameters:
                    environment: ${{variables.envProd}}
                    subscriptionId: ${{variables.subscriptionId}}
                    kvServiceConnection: ${{variables.kvServiceConnectionProd}}
