trigger:
  - develop

pool:
  vmImage: ubuntu-latest

variables:
  tenantId: 90598989-b884-4fc1-999f-d176a8e1a54e
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  environment: dev
  subscriptionIdDev: 94e4237e-953e-4c21-9a4e-fc3f3699d9e4
  subscriptionIdProd: f01f288f-34a3-415e-bbb3-f94336f6f6dd
  kvServiceConnectionDev: DEV KV Service Connection
  kvServiceConnectionProd: PROD KV Service Connection
  apiUrlDev: 'https://api.dev.costoptix.com'
  apiUrlProd: 'https://api.costoptix.com'

stages:
  - stage: Build_Stage
    displayName: Build
    condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
    jobs:
      - job: Build
        displayName: Build
        steps:
          - script: |
              npm install
              npm run build-dev
            displayName: npm install, build
          - script: (cd build && zip -r $(Build.ArtifactStagingDirectory)/build-dev.zip .)
            displayName: Zip Deployment
            condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
          - publish: $(Build.ArtifactStagingDirectory)/build-dev.zip
            displayName: Publish Artifacts
            condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
            artifact: App-dev
  - stage: Test_Stage
    displayName: Run Cypress Tests
    jobs: !include cypress-testing.yaml

  - stage: Deploy_Stage
    displayName: Deploy
    dependsOn: Build_and_Test_Stage
    condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
    jobs:
      - deployment: DeployDevJob
        displayName: Deploy DEV
        environment: DEV-App
        strategy:
          runOnce:
            deploy:
              steps:
                - template: _template-deploy.yaml
                  parameters:
                    Env: $(environment)
                    SubscriptionId: $(subscriptionIdDev)
                    KVServiceConnection: $(kvServiceConnectionDev)
