trigger:
  - develop

pool:
  vmImage: ubuntu-latest

variables:
  tenantId: 90598989-b884-4fc1-999f-d176a8e1a54e
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  env: dev
  subscriptionId: 94e4237e-953e-4c21-9a4e-fc3f3699d9e4
  kvServiceConnection: DEV KV Service Connection
  apiUrl: 'https://api.dev.costoptix.com'

stages:
  - stage: Build_Dev_Stage
    displayName: Build Dev
    condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
    jobs:
      - job: BuildDev
        displayName: Build Dev
        steps:
          - script: |
              npm install
              npm run build-dev
            displayName: npm install, build
          - script: (cd build && zip -r $(Build.ArtifactStagingDirectory)/build-dev.zip .)
            displayName: Zip Deployment
            condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
          - publish: $(Build.ArtifactStagingDirectory)/build-dev.zip
            displayName: Publish Artifacts
            condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
            artifact: App-dev

  - stage: Deploy_Dev_Stage
    displayName: Deploy Dev
    dependsOn: Build_Dev_Stage
    condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
    jobs:
      - deployment: DeployDevJob
        displayName: Deploy DEV
        environment: DEV-App
        strategy:
          runOnce:
            deploy:
              steps:
                - template: _template-deploy.yaml
                  parameters:
                    Env: $(env)
                    SubscriptionId: $(subscriptionId)
                    KVServiceConnection: $(kvServiceConnection)
