trigger:
  - develop

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndTestStageDev
    displayName: Build and Test Dev
    condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
    jobs:
      - job: BuildAndTestJob
        displayName: Build and Test
        steps:
          - script: |
              npm install
              npm run build-dev
            displayName: npm install, build
          - script: |
              npm run test
            displayName: 'Test'
          - task: PublishTestResults@2
            displayName: Publish Test Results
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
              failTaskOnFailedTests: true
              mergeTestResults: true
          - script: (cd build && zip -r $(Build.ArtifactStagingDirectory)/build-dev.zip .)
            displayName: Zip Deployment
            condition: and(succeeded(), eq(variables.isPullRequest, 'false'))
