stages:
  # Build the application and install dependencies
  - stage: build
    jobs:
      - job: buildJob
        pool:
          vmImage: 'ubuntu-latest' # or another suitable agent pool
        steps:
          - script: |
              npm install
              npm run build-dev
            displayName: 'Build and install dependencies'

  # Build and push a Docker image of the application
  - stage: dockerize
    dependsOn: build
    jobs:
      - job: dockerizeJob
        pool:
          vmImage: 'ubuntu-latest' # or another suitable agent pool
        steps:
          - script: |
              docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
              docker build --build-arg NODE_ENV=development -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
              docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
            displayName: 'Build and push Docker image'

  # Run Cypress tests against the Docker image
  - stage: test
    dependsOn: dockerize
    jobs:
      - job: testJob
        pool:
          vmImage: 'ubuntu-latest' # or another suitable agent pool
        steps:
          - script: |
              docker run --rm -v $PWD:/app -w /app $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA npm install
              docker run --rm -v $PWD:/app -w /app -e CYPRESS_baseUrl=http://$CI_PROJECT_URL $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA npx cypress run
            displayName: 'Run Cypress tests'
