schedules:
  - cron: '0 0 * * *'
    displayName: Daily midnight run
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

variables:
  runE2ETests: true

stages:
  - stage: RunE2ETests
    displayName: Run e2e tests
    condition: and(succeeded(), eq(variables.isPullRequest, 'false'), eq(variables.runE2ETests, 'true'))
    jobs:
      - job: RunE2ETests
        displayName: Run E2E Tests
        steps:
          - template: ./templates/e2e-testing.yaml
            parameters:
              url: www.costoptix.com
